### ISSUE TITLE
Moneda en el charco

### ISSUE THREAD

**Issue by nataliapc** [nataliapc/aventuraoriginal_remastered#4]
Cada vez que examinas el charco, si no has cogido la moneda, te dice que descubres una moneda. En fin, se puede colegir que encuentras la misma una y otra vez, porque no la has cogido...

Hay que comprobar si ocurre así también en el original y evaluar si mejorarlo o no.

**Comment by Juanjoide** [comment]
En ST ocurre lo mismo. La lógica del programa es así. Mientras no cojas la moneda, la encuentras una y otra vez cada vez que examinas el charco.

**Comment by Utodev** [comment]
Corregido con el uso del flag 12, que se estaba usando a medias ya, y que he nombrado como fEncontradaMoneda
