### ISSUE TITLE
S1- Problema al salvar partida a disco/cinta

### ISSUE THREAD

**Issue by Juanjoide** [nataliapc/aventuraoriginal_remastered#7]
Al salvar la partida con SAVE Indica "Grabando posición en disco..." pide nombre de fichero, aparece el mensaje "Prepara la", espera pulsación de teclado, salva partida a cinta y entonces se completa el mensaje anterior con la palabra "cinta." tras lo que aparece en la misma línea, y sin espacio tras el punto, el mensaje "*Pulsa una tecla*".

**Comment by Utodev** [comment]
Corregido.
