### ISSUE TITLE
S1- Mensajes al morir

### ISSUE THREAD

**Issue by Juanjoide** [nataliapc/aventuraoriginal_remastered#8]
Al morir, aparece el mensaje "Has dado XX" siendo XX el número de órdenes y suena la marcha fúnebre, tras lo cual se completa la frase con "ordenes", faltando el punto final a la frase. El cursor ">" aparece justo tras la frase "¿Hace otra partidita?" y debería estar en la línea inferior a la misma.

**Comment by Utodev** [comment]
Esto está cambiado en la última versión, por lo que lo doy por cerrado.
